app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
Route::get('/', 'ActivationController@getFindInsured');
Route::get('/home', 'ActivationController@getFindInsured');
Route::get('home/index', ['as' =>'home/index', 'uses' => 'HomeController@index']);
Route::get('home/enter', ['as' =>'home/enter', 'uses' => 'HomeController@enter']);
Route::get('home/search', ['as' =>'home/search', 'uses' => 'HomeController@search']);
Route::get('github', ['as' =>'github', 'uses' => 'PdfController@github']);
Route::get('downloadpdf/{id}/{hist}/{doc}', ['as' =>'downloadpdf', 'uses' => 'PdfController@downloadpdf']);


//ruta para realizar busqueda de hospitales en la web.
Route::get('home/hospitals', ['as' => 'home/hospitals', 'uses'=>'HomeController@hospitals']);
Route::get('home/hospitalssearch', ['as' => 'home/hospitalssearch', 'uses'=>'HomeController@hospitalssearch']);
Route::get('home/show', ['as' => 'legal', 'uses'=>'HomeController@show']);
Route::get('home/adhesion', ['as' => 'adhesion', 'uses'=>'HomeController@adhesion']);


// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', ['as' =>'auth/login', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('auth/logout', ['as' => 'auth/logout', 'uses' => 'Auth\AuthController@getLogout']);

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', ['as' => 'auth/register', 'uses' => 'Auth\AuthController@postRegister']);
//Registro de Admin
Route::get('auth/findstaff', 'Auth\AuthController@getRegisterAdm');
Route::post('auth/registerAdm', ['as' => 'auth/registerAdm', 'uses' => 'Auth\AuthController@postRegisterAdm']);

// Password reset link request routes...
Route::get('password/email', ['as' => 'password/email', 'uses' => 'Auth\PasswordController@getEmail']);
Route::post('password/email', ['as' => 'password/postEmail', 'uses' => 'Auth\PasswordController@postEmail']);

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::get('reset', ['as' => 'personal/reset', 'uses' =>  'PersonalController@reset']);
Route::post('update', ['as' => 'personal/update', 'uses' =>  'PersonalController@updatepass']);



//rutas para el recurso Insured
Route::resource('insured','InsuredController');

//rutas para Busqueda
Route::resource('search','SearchController');
//una nueva ruta para guardar las opciones de los roles 
Route::get('search/store/{id}', ['as' => 'search/store', 'uses'=>'SearchController@store']);
//ruta para realizar busqueda de registros.
Route::post('search/search', ['as' => 'search/search', 'uses'=>'SearchController@search']);

//rutas de video
Route::post('video/buscar','VideoController@buscar');
Route::post('video/buscaraseg','VideoController@buscaraseg');

Route::resource('video','VideoController');


//rutas de report
Route::post('approveclaim', ['as' => 'report/approveclaim', 'uses'=>'ReportController@approveclaim']);
Route::post('background', ['as' => 'report/background', 'uses'=>'ReportController@background']);
Route::post('history', ['as' => 'report/history', 'uses'=>'ReportController@history']);
Route::post('report/siniestros', ['as' => 'report/siniestros', 'uses'=>'ReportController@siniestros']);
Route::post('report/calls', ['as' => 'report/calls', 'uses'=>'ReportController@calls']);
Route::get('report/showcalls', ['as' => 'report/showcalls', 'uses'=>'ReportController@showcalls']);
Route::resource('report','ReportController');

//ruta prueba sipml5
Route::get('sipml5route', function () {
return view('drsipml5/call');
});
Route::get('sip','sipml5@index');

Route::post('uploadAudio', ['as' => 'uploadAudio', 'uses'=>'UploadFileController@saveFile'] );

include_once("Routes/activation.php");
include_once("Routes/configuration.php");
include_once("Routes/pharmacy.php");
include_once("Routes/personal.php");
include_once("Routes/insurance.php");

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Insured;

class SearchController extends Controller
{
     protected $redirectTo = 'auth/login';
     public function __construct() {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $info = Insured::all();
        return \View::make('search/search',compact('info'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function search(Request $request){
         $info = Insured::where('identity_number','=',$request->id_number)->get();
         return \View::make('search/search', compact('info'));
        
    }
}

resources/views/search/history2.blade.php
@extends('app')

@section('content')
<div class="container">
    <div class="page-header">
        <h1>Detalle del Historial</h1>
    </div>
    <div class="row">
        <div class="all" style="display: inline;">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">Detalle del Historial</div>                    
                        <div class="panel-body">
                            <br>
                            {!! Form::open(['class' => 'form']) !!}
                            <table class="table table-condensed table-striped table-bordered">                                
                                <tbody>
                                	<div class="form-group">
                                        <label>Fecha de tratamiento</label>
                                        {!! Form::input('text', 'created', date_format( $history->created_at, 'd/m/Y H:i:s'), ['class'=> 'form-control']) !!}                            
                                    </div>
                                    <div class="form-group">
                                        <label>Motivo de la Consulta</label>
                                        {!! Form::input('text', 'reason', $history->reason, ['class'=> 'form-control']) !!}                            
                                    </div>
                                    <div class="form-group">
                                        <label>Diagnostico</label>
                                        {!! Form::input('text', 'current_illness', $history->current_illness, ['class'=> 'form-control']) !!}                            
                                    </div>
                                    <div class="form-group">
                                        <label>Tratamiento a seguir:</label>
                                        {!! Form::input('text', 'treatment', $history->treatment, ['class'=> 'form-control']) !!}                            
                                    </div>  
                                    <div class="form-group">
                                        <label>Sugerencias y recomendaciones:</label>
                                        {!! Form::input('text', 'suggestion', $history->suggestion, ['class'=> 'form-control']) !!}                            
                                    </div> 
                                    <div class="form-group">
                                        <label>Indicaciones:</label>
                                        {!! Form::input('text', 'indications', $history->indications, ['class'=> 'form-control']) !!}                            
                                    </div> 
                                    <div class="form-group">
                                        <label>Examenes complementarios:</label>
                                        {!! Form::input('text', 'exam', $history->exam, ['class'=> 'form-control']) !!}                            
                                    </div>      
                                    <div class="form-group">
                                        <label>Receta medica</label>
                                        {!! Form::input('text', 'prescription', $history->prescription, ['class'=> 'form-control']) !!}                            
                                    </div>      
                                    <div class="form-group">
                                        <label>Clinica a Referir:</label>
                                        {!! Form::input('text', 'doctor_reference', $history->doctor_reference, ['class'=> 'form-control']) !!}                            
                                    </div> 
                                    <div class="form-group">
                                        <label>Motivo de la referencia:</label>
                                        {!! Form::input('text', 'reference_reason', $history->reference_reason, ['class'=> 'form-control']) !!}                            
                                    </div>                                                  
                                                                                    
                                </tbody>
                            </table>    

                    <div>
                        <a href="{{ URL::previous() }}" class="btn btn-success">Volver</a>                      
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/search/history_report.blade.php
@extends('app')
@section('content')
<div class="container">
  <div class="page-header">
      <div class="page-header">
      <div align="center"><img src="{{ asset('images/img/asegurado.png') }}" class="img-responsive" alt="">
  <h1>Historia del Asegurado</h1>
  </div>

<div class="row">
        <div class="all" style="display: inline;">
            <div class="row">
                <div class="col-md-12 ">
                    <div class="panel panel-default">
                        <div class="panel-heading"></div>

                        <div class="panel-body">                 
                            {!! Form::open(['novalidate', 'class' => 'form-inline']) !!}
                            <div class="form-group">
                            <label for="name">Asegurado</label>
                               {!! Form::input('text', 'name', $per->first_name . ' ' . $per->last_name , ['class'=> 'form-control']) !!}
                            </div>
                             <div class="form-group">
                            <label for="identity_number">Código de Póliosa</label>
                                {!! Form::input('text', 'name', $per->policy_number , ['class'=> 'form-control'] ) !!}
                            </div>
                             <div class="form-group">
                            
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div> 


    <div class="row">
               <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a href="{{ URL::previous() }}" class="btn btn-success">Volver</a>
                            <a href="{{ route('reportinsured',['id' => $per->id] ) }}" class="btn btn-primary">Todos</a>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                         <tr>
                                            <th></th>
                                            <th>Fecha de ingreso</th>
                                            <th>Motivo del ingreso</th>
                                            <th>Antecedentes</th>
                                            <th>Clinca a Referir</th>
                                            <th>{{ trans('nav.action') }}</th  
                                          </tr>
                                    </thead>
                                   <tbody>
                                        @foreach($info as $i)
                                        <tr>
                                            <td>{{ $i->id }}</td>
                                            <td>{{date_format( $i->created_at, 'd/m/Y H:i:s') }}</td>
                                            <td>{{ $i->reason }}</td>
                                            <td>{{ $i->background }}</td>
                                            <td>{{ $i->doctor_reference }}</td>
                                            <td>
                                             <a class="glyphicon glyphicon-eye-open" title='Ver Detalle.'href="{{ route('history/detail',['id' => $i->id] )}}" > </a>
                                            </td>
                                           
                                        </tr>
                                        @endforeach
                                    </tbody> 
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
   
  </div> <!-- /. ROW-->
</div>
{!! Html::script('assets/bower_components/jquery/dist/jquery.min.js') !!}

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
@endsection

resources/views/search/search.blade.php
@extends('app')
@section('content')
<div class="container">
  <div class="page-header">
      <div class="page-header">
      <div align="center"><img src="{{ asset('images/img/asegurado.png') }}" class="img-responsive" alt="">
  <h1>Busqueda de Asegurado Registrado</h1>
  </div>
    <div class="row">
               <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            
                              <a href="{{ route('search.index') }}" class="btn btn-primary">All</a>
                            
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                         <tr>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Cedula</th>
                                            <th>Nro de poliza</th>
                                            <th>{{ trans('nav.action') }}</th>  

                                          </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($info as $i)
                                        <tr>
                                            <td>{{ $i->first_name }}</td>
                                            <td>{{ $i->last_name }}</td>
                                            <td>{{ $i->identity_number }}</td>
                                            <td>{{ $i->policy_number }}</td>
                                            <td>
                                             <a class="glyphicon glyphicon-eye-open" title='Ver Historial'href="{{ route('reportinsured',['id' => $i->id] )}}" > </a>
                                            </td>
                                           
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
   
  </div> <!-- /. ROW-->
</div>
{!! Html::script('assets/bower_components/jquery/dist/jquery.min.js') !!}

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });
    </script>
@endsection